import React, { useState } from 'react';
import { TemplateSettings, SectionId, RoleTemplateConfig } from '../types';
import {
  PRESET_ROLE_TEMPLATES,
  ROLE_CATEGORIES,
  matchRoleTemplate,
} from '../data/roleTemplates';
import {
  Sparkles,
  Search,
  Check,
  ArrowRight,
  Briefcase,
  HelpCircle,
  Wand2,
  Sliders,
  Compass,
  FileCheck2,
  RotateCcw,
} from 'lucide-react';

interface RoleTemplateSelectorProps {
  currentSettings: TemplateSettings;
  currentTitle?: string;
  onApplyRoleTemplate: (config: RoleTemplateConfig, reorderSections: boolean) => void;
  compactMode?: boolean;
}

export const RoleTemplateSelector: React.FC<RoleTemplateSelectorProps> = ({
  currentSettings,
  currentTitle = '',
  onApplyRoleTemplate,
  compactMode = false,
}) => {
  const [searchRole, setSearchRole] = useState<string>(
    currentSettings.appliedRoleName || currentTitle || 'Software & DevOps Engineer'
  );
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [shouldReorderSections, setShouldReorderSections] = useState<boolean>(true);
  const [isAiGenerating, setIsAiGenerating] = useState<boolean>(false);
  const [aiError, setAiError] = useState<string | null>(null);

  // Active matched config (defaults to instant client-side match)
  const [activeConfig, setActiveConfig] = useState<RoleTemplateConfig>(() => {
    return matchRoleTemplate(
      currentSettings.appliedRoleName || currentTitle || 'Software & DevOps Engineer'
    );
  });

  const handleRoleInputChange = (val: string) => {
    setSearchRole(val);
    setSelectedCategory(null);
    setAiError(null);
    const matched = matchRoleTemplate(val);
    setActiveConfig(matched);
  };

  const handleSelectPreset = (config: RoleTemplateConfig) => {
    setSearchRole(config.roleTitle);
    setSelectedCategory(config.category);
    setActiveConfig(config);
    setAiError(null);
  };

  const handleUseCurrentTitle = () => {
    if (currentTitle) {
      handleRoleInputChange(currentTitle);
    }
  };

  // Call Gemini AI endpoint for deep custom role tailoring
  const handleAiTailorForRole = async () => {
    if (!searchRole.trim()) return;
    setIsAiGenerating(true);
    setAiError(null);

    try {
      const res = await fetch('/api/ai/recommend-template-for-role', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ role: searchRole }),
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData.error || 'Failed to tailor template via AI');
      }

      const data = await res.json();

      // Build RoleTemplateConfig from AI response
      const aiConfig: RoleTemplateConfig = {
        roleTitle: searchRole,
        category: data.industryCategory || 'AI Tailored Custom Role',
        description: `Custom ATS template generated by Gemini for "${searchRole}".`,
        rationale: data.roleRationale || 'Optimized for modern industry recruitment norms and ATS parsing.',
        keyTips: data.keyTips || [
          'Highlight quantitative metrics relevant to this specific role.',
          'Verify key technical competencies in early sections.',
        ],
        recommendedSectionOrder: (data.recommendedSectionOrder || [
          'summary',
          'skills',
          'experience',
          'projects',
          'education',
          'certifications',
        ]) as SectionId[],
        settings: {
          preset: data.preset || 'modern-tech',
          fontFamily: data.fontFamily || 'Inter',
          baseFontSize: data.baseFontSize || 12.8,
          lineHeight: data.lineHeight || 1.42,
          pageMargin: data.pageMargin || 14,
          sectionGap: data.sectionGap || 14,
          itemGap: data.itemGap || 9,
          primaryColor: data.primaryColor || '#1e40af',
          textColor: '#0f172a',
          headerStyle: data.headerStyle || 'left-accent',
          bulletStyle: data.bulletStyle || 'disc',
          columnLayout: data.columnLayout === 'two-column-hybrid' ? 'two-column-hybrid' : 'single',
          paperSize: 'letter',
          uppercaseHeadings: data.uppercaseHeadings !== false,
          showDividers: true,
          highlightKeywords: true,
          appliedRoleName: searchRole,
        },
      };

      setActiveConfig(aiConfig);
    } catch (err: any) {
      console.error('AI Role Tailor error:', err);
      setAiError(err.message || 'AI tailoring failed. Falling back to rule-based template.');
      // Keep client-side match as fallback
    } finally {
      setIsAiGenerating(false);
    }
  };

  const handleApply = () => {
    onApplyRoleTemplate(activeConfig, shouldReorderSections);
  };

  return (
    <div className="space-y-4">
      {/* Search and Input Bar */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <label className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
            <Briefcase className="w-3.5 h-3.5 text-blue-600" />
            <span>Target Job Role</span>
          </label>
          {currentTitle && currentTitle !== searchRole && (
            <button
              onClick={handleUseCurrentTitle}
              className="text-[11px] text-blue-600 hover:text-blue-800 font-medium flex items-center gap-1 transition-colors"
            >
              <span>Use Resume Title ("{currentTitle.slice(0, 22)}{currentTitle.length > 22 ? '...' : ''}")</span>
            </button>
          )}
        </div>

        <div className="relative flex items-center gap-2">
          <div className="relative flex-1">
            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchRole}
              onChange={(e) => handleRoleInputChange(e.target.value)}
              placeholder="Type any role: e.g. Cloud Architect, ICU Nurse, Lawyer, Art Director..."
              className="w-full pl-8 pr-3 py-2 text-xs rounded-xl border border-slate-300 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 bg-white"
            />
          </div>

          <button
            onClick={handleAiTailorForRole}
            disabled={isAiGenerating || !searchRole.trim()}
            className="px-3 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white rounded-xl text-xs font-semibold shadow-2xs flex items-center gap-1.5 transition-all disabled:opacity-50 shrink-0 cursor-pointer"
            title="Ask Gemini AI to analyze this role and design the ideal ATS template"
          >
            {isAiGenerating ? (
              <>
                <div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                <span className="hidden sm:inline">AI Tailoring...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5" />
                <span>AI Tailor</span>
              </>
            )}
          </button>
        </div>

        {aiError && (
          <p className="text-[11px] text-amber-600 bg-amber-50 p-2 rounded-lg border border-amber-200">
            {aiError}
          </p>
        )}
      </div>

      {/* Popular Role Category Pills */}
      <div className="space-y-1.5">
        <span className="text-[11px] font-semibold text-slate-500">Popular Industry Templates:</span>
        <div className="flex flex-wrap gap-1.5">
          {PRESET_ROLE_TEMPLATES.map((preset) => {
            const isSelected = activeConfig.roleTitle === preset.roleTitle;
            return (
              <button
                key={preset.roleTitle}
                onClick={() => handleSelectPreset(preset)}
                className={`px-2.5 py-1 rounded-lg text-xs font-medium transition-all text-left flex items-center gap-1.5 border ${
                  isSelected
                    ? 'bg-blue-50 border-blue-400 text-blue-800 shadow-2xs font-semibold ring-1 ring-blue-400/30'
                    : 'bg-white hover:bg-slate-50 border-slate-200 text-slate-700'
                }`}
              >
                <span
                  className="w-2 h-2 rounded-full shrink-0"
                  style={{ backgroundColor: preset.settings.primaryColor }}
                />
                <span className="truncate max-w-[150px]">{preset.roleTitle}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Matched Role Details Card */}
      <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200/90 space-y-3">
        <div className="flex items-start justify-between gap-2">
          <div>
            <div className="flex items-center gap-2">
              <span className="font-bold text-slate-900 text-xs sm:text-sm">
                {activeConfig.roleTitle}
              </span>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-blue-100 text-blue-800 font-semibold border border-blue-200">
                {activeConfig.category}
              </span>
            </div>
            <p className="text-[11px] text-slate-600 mt-1 leading-relaxed">
              {activeConfig.description}
            </p>
          </div>
        </div>

        {/* Visual Attributes Matrix */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-1 border-t border-slate-200/70 text-[11px]">
          <div className="bg-white p-2 rounded-lg border border-slate-200">
            <span className="text-slate-400 text-[10px] block">Typography</span>
            <span className="font-semibold text-slate-800 truncate block" title={activeConfig.settings.headingFontFamily ? `${activeConfig.settings.headingFontFamily} + ${activeConfig.settings.fontFamily}` : activeConfig.settings.fontFamily}>
              {activeConfig.settings.headingFontFamily && activeConfig.settings.headingFontFamily !== activeConfig.settings.fontFamily
                ? `${activeConfig.settings.headingFontFamily} + ${activeConfig.settings.fontFamily}`
                : activeConfig.settings.fontFamily}
            </span>
          </div>

          <div className="bg-white p-2 rounded-lg border border-slate-200 flex items-center justify-between">
            <div>
              <span className="text-slate-400 text-[10px] block">Accent Color</span>
              <span className="font-mono text-[10px] font-semibold text-slate-800">
                {activeConfig.settings.primaryColor}
              </span>
            </div>
            <div
              className="w-4 h-4 rounded-full border border-slate-300 shadow-2xs"
              style={{ backgroundColor: activeConfig.settings.primaryColor }}
            />
          </div>

          <div className="bg-white p-2 rounded-lg border border-slate-200">
            <span className="text-slate-400 text-[10px] block">Header Style</span>
            <span className="font-semibold text-slate-800 capitalize">
              {activeConfig.settings.headerStyle.replace('-', ' ')}
            </span>
          </div>

          <div className="bg-white p-2 rounded-lg border border-slate-200">
            <span className="text-slate-400 text-[10px] block">Bullet Style</span>
            <span className="font-semibold text-slate-800 capitalize">
              {activeConfig.settings.bulletStyle}
            </span>
          </div>
        </div>

        {/* Recruiter & ATS Rationale */}
        <div className="bg-blue-50/70 border border-blue-200/80 rounded-lg p-2.5 text-xs text-blue-950 space-y-1">
          <div className="flex items-center gap-1 font-semibold text-blue-900 text-[11px]">
            <Compass className="w-3 h-3 text-blue-600" />
            <span>Recruiter & ATS Strategic Fit:</span>
          </div>
          <p className="text-[11px] text-blue-900 leading-relaxed">
            {activeConfig.rationale}
          </p>
        </div>

        {/* Actionable Hiring Tips */}
        {activeConfig.keyTips && activeConfig.keyTips.length > 0 && (
          <div className="space-y-1 text-[11px]">
            <span className="font-semibold text-slate-700 flex items-center gap-1">
              <FileCheck2 className="w-3 h-3 text-emerald-600" />
              <span>Hiring Manager Recommendations for this Role:</span>
            </span>
            <ul className="list-disc list-inside space-y-0.5 text-slate-600 pl-1">
              {activeConfig.keyTips.map((tip, idx) => (
                <li key={idx} className="leading-snug">{tip}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Section Reorder Option */}
        <div className="pt-2 border-t border-slate-200/70 flex items-center justify-between">
          <label className="flex items-center gap-2 cursor-pointer text-[11px] text-slate-700">
            <input
              type="checkbox"
              checked={shouldReorderSections}
              onChange={(e) => setShouldReorderSections(e.target.checked)}
              className="w-3.5 h-3.5 text-blue-600 rounded border-slate-300 focus:ring-blue-500"
            />
            <span>
              Rearrange sections to highlight what recruiters for this role expect first
            </span>
          </label>
        </div>

        {/* Recommended Order Preview */}
        {shouldReorderSections && (
          <div className="flex flex-wrap items-center gap-1 text-[10px] text-slate-500 bg-white p-2 rounded-lg border border-slate-200">
            <span className="font-semibold text-slate-700">Recommended hierarchy:</span>
            {activeConfig.recommendedSectionOrder.map((sec, i) => (
              <React.Fragment key={sec}>
                <span className="px-1.5 py-0.5 bg-slate-100 rounded text-slate-800 font-medium capitalize">
                  {sec}
                </span>
                {i < activeConfig.recommendedSectionOrder.length - 1 && (
                  <ArrowRight className="w-2.5 h-2.5 text-slate-400" />
                )}
              </React.Fragment>
            ))}
          </div>
        )}

        {/* Apply Button */}
        <div className="pt-2">
          <button
            onClick={handleApply}
            className="w-full py-2.5 px-4 bg-slate-900 hover:bg-black text-white text-xs font-semibold rounded-xl shadow-xs transition-colors flex items-center justify-center gap-2 cursor-pointer"
          >
            <Check className="w-4 h-4 text-emerald-400" />
            <span>Apply Template for {activeConfig.roleTitle}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
